name: Go build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/icecon-linux-amd64 -v .
          GOOS=linux GOARCH=arm64 go build -o dist/icecon-linux-arm64 -v .
          GOOS=linux GOARCH=386 go build -o dist/icecon-linux-i386 -v .
          GOOS=windows GOARCH=amd64 go build -o dist/icecon-windows.exe -v .

      - name: ls
        run: ls -la dist/
      
      - name: Upload build to to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: "1.0.1"
          overwrite: true
          file_glob: true
